export default function handler(req, res) {
    res.status(200).json([
        /* event music */
        {
            activityId: 5072,
            activityType: 2202,
            scheduleId: 5072001,
            beginTime: 0,
            endTime: 1924992000,
            meetCondList: [5072001, 5072002, 5072003, 5072004, 5072005, 5072006, 5072007, 5072008, 5072009, 5072013],
        },
        /* new event */
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5093,
            activity_type: 2100,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 0,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1924992000,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1661284800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5093001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: true,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {
                143: 0,
                144: 0,
            },
            activity_id: 2015,
            activity_type: 3000,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 0,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1924992000,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1661198400,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [
                        {
                            is_open: false,
                            stage_id: 1,
                        },
                        {
                            is_open: false,
                            stage_id: 2,
                        },
                        {
                            is_open: false,
                            stage_id: 3,
                        },
                        {
                            is_open: false,
                            stage_id: 4,
                        },
                    ],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [
                        {
                            is_finished: false,
                            is_open: false,
                            stage_id: 1,
                        },
                        {
                            is_finished: false,
                            is_open: false,
                            stage_id: 2,
                        },
                        {
                            is_finished: false,
                            is_open: false,
                            stage_id: 3,
                        },
                        {
                            is_finished: false,
                            is_open: false,
                            stage_id: 4,
                        },
                    ],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [
                        {
                            is_open: false,
                            level_id: 1,
                            max_score: 0,
                        },
                        {
                            is_open: false,
                            level_id: 2,
                            max_score: 0,
                        },
                        {
                            is_open: false,
                            level_id: 3,
                            max_score: 0,
                        },
                        {
                            is_open: false,
                            level_id: 4,
                            max_score: 0,
                        },
                        {
                            is_open: false,
                            level_id: 5,
                            max_score: 0,
                        },
                        {
                            is_open: false,
                            level_id: 6,
                            max_score: 0,
                        },
                        {
                            is_open: false,
                            level_id: 7,
                            max_score: 0,
                        },
                    ],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [
                        {
                            is_finished: false,
                            is_open: false,
                            level_id: 1,
                            stage_id: 1,
                        },
                        {
                            is_finished: false,
                            is_open: false,
                            level_id: 6,
                            stage_id: 2,
                        },
                        {
                            is_finished: false,
                            is_open: false,
                            level_id: 11,
                            stage_id: 3,
                        },
                        {
                            is_finished: false,
                            is_open: false,
                            level_id: 16,
                            stage_id: 4,
                        },
                    ],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [2015006, 2015012, 2015013],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 2015001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015321,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015320,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015319,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015318,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015317,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015316,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015303,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015109,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015302,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015108,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015103,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 4,
                    watcher_id: 12015403,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015209,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015112,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015306,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015003,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015102,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 4,
                    watcher_id: 12015004,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015101,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015402,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015111,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015305,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 2,
                    watcher_id: 12015002,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015404,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015113,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015307,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015210,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 2,
                    watcher_id: 12015401,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015110,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015304,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015001,
                },
                {
                    cur_progress: 1,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015202,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015105,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015203,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015106,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015301,
                },
                {
                    cur_progress: 1,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015204,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015107,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015104,
                },
                {
                    cur_progress: 1,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015201,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015405,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015114,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015211,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015308,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015406,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015115,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015212,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015309,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015407,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015116,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015310,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015408,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015117,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015311,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015409,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015118,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015312,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015410,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015119,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015313,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 2,
                    watcher_id: 12015411,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015120,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015314,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 3,
                    watcher_id: 12015412,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12015315,
                },
            ],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5086,
            activity_type: 2100,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 0,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1924992000,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1661284800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5086001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5092,
            activity_type: 8,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 0,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1924992000,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1661284800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5092001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
    ]);
}
