export default function handler(req, res) {
    // Note: remove event 5002 because trial event is useless
    res.status(200).json([
        /* event music */
        {
            activityId: 5072,
            activityType: 2202,
            scheduleId: 5072001,
            beginTime: 0,
            endTime: 1924992000,
            meetCondList: [5072001, 5072002, 5072003, 5072004, 5072005, 5072006, 5072007, 5072008, 5072009, 5072013],
        },
        /* new event */
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5105,
            activity_type: 2100,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 1664319600,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1667343600,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1664308800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5105001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5104,
            activity_type: 2100,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 1664319600,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1665741540,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1664308800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5104001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5102,
            activity_type: 2100,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 1664319600,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1667343600,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1664308800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5102001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: false,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {},
            activity_id: 5100,
            activity_type: 8,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 1664319600,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1665741540,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1664308800,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 5100001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            watcher_info_list: [],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
        {
            Unk2700_EDKLLHBEEGE: false,
            Unk2700_IFPBCNLCKLG: [],
            Unk2700_NONJFHAIFLA: true,
            Unk2800_KOMIPKKKOBE: [],
            activity_coin_map: {
                147: 0,
                148: 0,
                149: 0,
                150: 0,
            },
            activity_id: 2016,
            activity_type: 3103,
            arena_challenge_info: {
                Unk2800_GNKHCICOIMC: false,
                level_list: [],
                level_open_time_map: {},
                world_level: 0,
            },
            aster_info: {
                aster_credit: 0,
                aster_large: {
                    begin_time: 0,
                    is_open: false,
                },
                aster_little: {
                    begin_time: 0,
                    is_open: false,
                    stage_begin_time: 0,
                    stage_id: 0,
                    stage_state: "ASTER_LITTLE_STAGE_STATE_NONE",
                },
                aster_mid: {
                    begin_time: 0,
                    camp_list: [],
                    collect_count: 0,
                    is_open: false,
                },
                aster_progress: {
                    count: 0,
                    last_auto_add_time: 0,
                },
                aster_token: 0,
                content_close_time: 0,
                is_content_closed: false,
                is_special_reward_taken: false,
            },
            bartender_info: {
                Unk2700_AIKFMMLFIJI: [],
                Unk2700_BMOAIJMHPGA: [],
                Unk2700_DAGGAECBDEG: [],
                Unk2700_JICAAEMPNBC: false,
                Unk2700_MEGOPKBEHOH: [],
                is_content_closed: false,
            },
            begin_time: 1664416800,
            blessing_info: {
                content_close_time: 0,
                cur_day_scan_num: 0,
                cur_day_scan_type: 0,
                is_activated: false,
                is_content_closed: false,
                next_refresh_time: 0,
                pic_num_map: {},
                redeem_reward_num: 0,
            },
            blitz_rush_info: {
                content_close_time: 0,
                is_content_closed: false,
                parkour_level_info_list: [],
                stage_list: [],
            },
            bounce_conjuring_info: {
                chapter_info_list: [],
                content_close_time: 0,
                is_content_closed: false,
            },
            buoyant_combat_info: {
                daily_info_list: [],
            },
            channeler_slab_info: {
                buff_info: {
                    assist_info_list: [],
                    buff_id_list: [],
                    mp_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                    single_buff_scheme_info: {
                        self_energy: 0,
                        slot_map: {},
                        total_energy: 0,
                    },
                },
                loop_dungeon_stage_info: {
                    dungeon_info_list: [],
                    is_open: false,
                    last_difficulty_id: 0,
                    open_time: 0,
                    taken_reward_index_list: [],
                },
                play_end_time: 0,
                stage_list: [],
            },
            chess_info: {
                available_exp: 0,
                content_close_time: 0,
                exp: 0,
                finished_map_id_list: [],
                is_content_closed: false,
                is_teach_dungeon_finished: false,
                level: 0,
                obtained_exp: 0,
                punish_over_time: 0,
            },
            crucible_info: {
                battle_world_level: 0,
                cost_time: 0,
                pos: {
                    x: 0,
                    y: 0,
                    z: 0,
                },
                uid_info_list: [],
            },
            crystal_link_info: {
                Unk2700_FIKHCFMEOAJ: [],
                difficulty_id: 0,
            },
            cur_score: 0,
            delivery_info: {
                day_index: 0,
                finished_delivery_quest_index: [],
                is_taken_reward: false,
            },
            dig_info: {
                dig_mark_point_list: [],
                stage_id: 0,
                stage_id_list: [],
            },
            dragon_spine_info: {
                chapter_info_list: [],
                content_finish_time: 0,
                is_content_closed: false,
                shimmering_essence: 0,
                warm_essence: 0,
                weapon_enhance_level: 0,
                wondrous_essence: 0,
            },
            echo_shell_info: {
                Unk2800_BFONDMJGNKL: [],
                Unk2800_KEMCFBCAMMM: [],
                shell_list: [],
                taken_reward_list: [],
            },
            effigy_info: {
                cur_score: 0,
                daily_info_list: [],
                last_difficulty_id: 0,
                taken_reward_index_list: [],
            },
            end_time: 1666555199,
            expedition_info: {
                challenge_info_list: [],
                content_close_time: 0,
                cur_challenge_id: 0,
                expedition_count: 0,
                is_content_closed: false,
                path_info_list: [],
            },
            expire_cond_list: [],
            find_hilichurl_info: {
                content_close_time: 0,
                day_content_info_list: [],
                day_index: 0,
                is_content_closed: false,
                is_end_quest_accept: false,
                min_open_player_level: 0,
                player_day_index: 0,
            },
            first_day_start_time: 1664395200,
            fleur_fair_info: {
                chapter_info_list: [],
                content_close_time: 0,
                dungeon_punish_over_time: 0,
                dungeon_section_info_map: {},
                is_content_closed: false,
                is_dungeon_unlocked: false,
                minigame_info_map: {},
                obtained_token: 0,
            },
            flight_info: {
                daily_record_list: [],
                min_open_player_level: 0,
                preview_reward_id: 0,
            },
            gacha_info: {
                Unk2700_CDPAPBIOPCA: 0,
                Unk2700_DACHHINLDDJ: [],
                Unk2700_FGFGLDIJJEK: 0,
                Unk2700_KOHKBCABICD: [],
                Unk2700_PIDHKNLDALB: [],
                gacha_stage_list: [],
            },
            gear_info: {
                Unk2800_GBAPCBPMHNJ: [],
                Unk2800_IHEHGOBCINC: {
                    Unk2800_MGPEODNKEEC: 0,
                    Unk2800_MMPELBBNFOD: 0,
                    is_finished: false,
                    is_open: false,
                },
            },
            graven_innocence_info: {
                Unk3000_BDFIOPBIOEB: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_FJENMMCFMGD: 0,
                    Unk3000_HKABHFLDNKF: [],
                },
                Unk3000_CDDIFHNEDOO: {
                    Unk2700_PHKHIPLDOOA: [],
                    Unk3000_AIENCMLMCBE: [],
                },
                Unk3000_JGJKABIPGLK: {
                    Unk2700_FIKHCFMEOAJ: [],
                },
                Unk3000_KDPJGGENAJM: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                is_content_closed: false,
            },
            hachi_info: {
                stage_map: {},
            },
            hide_and_seek_info: {
                Unk2700_JDMDOOHFNCA: [],
                chosen_hider_skill_list: [],
                chosen_hunter_skill_list: [],
                unlock_map_list: [],
            },
            instable_spray_info: {
                Unk2700_PHKHIPLDOOA: [],
            },
            irodori_info: {
                Unk2700_AGGJBDLONGC: {
                    Unk2700_AEJIIOOPJIL: [],
                    Unk2700_HNCBHBKDODH: 0,
                },
                Unk2700_BFPBLJAAPAL: {
                    Unk2700_ANAEHLBDFIC: [],
                    Unk2700_PMMJDKJHBIG: [],
                },
                Unk2700_KLDGOEPJGNC: [],
                Unk2700_MCMCCIEFMPD: {
                    Unk2700_KPEIIFDINPC: [],
                    is_open: false,
                },
            },
            is_finished: false,
            is_hidden: false,
            is_play_open_anim: false,
            is_starting: false,
            island_party_info: {
                Unk2800_PDBHCBCLFBM: [],
            },
            lantern_rite_activity_info: {
                Unk2700_EOGEAIHJPFD: false,
                Unk2700_KGGCKHBIOED: false,
                Unk2700_MPOCLGBFNAK: {
                    Unk2700_PHKHIPLDOOA: [],
                },
                Unk2700_ONOHODJPIGK: {
                    Unk2700_CPJMLMCOCLA: [],
                    Unk2700_EGPCJLGGGLK: [],
                    Unk2700_OCBDODAGPNF: [],
                    level_list: [],
                },
                Unk2700_PHKHIPLDOOA: [],
                is_content_closed: false,
            },
            luminance_stone_challenge_info: {
                Unk2700_CKGMNLPDFCI: false,
                Unk2700_NNLBIAFMHPA: 0,
                best_score: 0,
                is_content_closed: false,
            },
            luna_rite_info: {
                area_info_list: [],
                hint_point: [],
            },
            meet_cond_list: [2016001, 2016002, 2016036],
            michiae_matsuri_info: {
                Unk2700_BEHAAHHGCLK: [],
                Unk2700_LEKHKNKHIPO: [],
                Unk2700_MAOAHHBCKIA: 0,
                Unk2700_MPNNMCPOLAM: [],
                stage_list: [],
            },
            mist_trial_activity_info: {
                trial_level_data_list: [],
            },
            moonfin_trial_info: {
                level_info_map: {},
                special_fish_count: 0,
            },
            muqadas_potion_info: {
                Unk3000_IBEFNBFGAOP: [],
            },
            music_game_info: {
                music_game_record_map: {},
                others_custom_beatmap: [],
                person_custom_beatmap: [],
            },
            photo_info: {
                is_content_closed: false,
                photo_stage_list: [],
            },
            plant_flower_info: {
                day_index: 0,
                is_content_closed: false,
                is_today_has_awarded: false,
                today_seed_reward_id: 0,
                used_flower_num_map: {},
                wish_flower_num_map: {},
            },
            potion_info: {
                stage_list: [],
            },
            rogue_diary_info: {
                cur_progress: {
                    Unk2700_EGBDDLOBCDL: [],
                    Unk2700_MMFHBHNKLDG: false,
                    Unk2700_PPEBOKBCPLE: 0,
                    difficulty: 0,
                    stage_id: 0,
                },
                is_content_closed: false,
                is_have_progress: false,
                stage_list: [],
            },
            roguelike_dungeon_info: {
                content_close_time: 0,
                equipped_rune_list: [],
                is_content_closed: false,
                rune_list: [],
                shikigami_list: [],
                stage_list: [],
            },
            salesman_info: {
                cond_day_count: 0,
                day_index: 0,
                day_reward_id: 0,
                deliver_count: 0,
                is_has_taken_special_reward: false,
                is_today_has_delivered: false,
                last_deliver_time: 0,
                selected_reward_id_map: {},
                special_reward_preview_id: 0,
                status: "SALESMAN_STATUS_TYPE_NONE",
            },
            sam_lamp_info: {
                contribution: 0,
                days: 0,
                factor: 0,
                phase_id: 0,
                progress: 0,
                taken_contribution_reward_list: [],
                taken_phase_reward_list: [],
            },
            schedule_id: 2016001,
            score_limit: 0,
            sea_lamp_info: {
                day_index: 0,
                first_day_start_time: 0,
                is_content_closed: false,
                is_mechanicus_feature_close: false,
                is_mechanicus_open: false,
                mechanicus_id: 0,
                popularity: 0,
                sea_lamp_coin: 0,
                section_info_list: [],
            },
            selected_avatar_reward_id: 0,
            spice_info: {
                Unk2700_IGMHNDNGNPG: 0,
                Unk2700_KIAHJKGOLGO: 0,
                spice_stage_list: [],
            },
            summer_time_info: {
                content_close_time: 0,
                is_content_closed: false,
                sprint_boat_info: {
                    record_list: [],
                },
                stage_map: {},
            },
            summer_time_v2_info: {
                Unk2800_ELHBCNPKOJG: 0,
                Unk2800_HDEFJKGDNEH: 0,
                Unk2800_MPKLJJIEHIB: [],
                Unk2800_PNBLCPIBKPO: [],
                is_content_closed: false,
            },
            sumo_info: {
                Unk2700_NIJIAJMFLLD: 0,
                difficulty_id: 0,
                sumo_stage_map: {},
            },
            taken_reward_list: [],
            tanuki_travel_activity_info: {
                Unk2700_BHHCNOLMCJM: 0,
                Unk2700_JBPFIDDPGME: [],
                is_content_closed: false,
            },
            treasure_map_info: {
                active_region_index: 0,
                bonus_challenge_list: [],
                currency_num: 0,
                is_mp_challenge_touched: false,
                min_open_player_level: 0,
                preview_reward_id: 0,
                region_info_list: [],
                total_mp_spot_num: 0,
                treasure_close_time: 0,
            },
            treasure_seelie_info: {
                Unk3000_NMEPJANNLLE: [],
                is_content_closed: false,
                treasure_close_time: 0,
            },
            trial_avatar_info: {
                reward_info_list: [],
            },
            ugc_info: {
                Unk2700_FDDCMGKDOCC: 0,
                Unk2700_GMICFADLAMC: false,
                Unk2700_ILCAPJBAFOI: [],
                Unk2700_PNOCELCOFNK: false,
            },
            "unk_lgroup[445]": {
                "unk_lgroup[13]": {
                    "unk_lgroup[2]": {
                        "unk_lgroup[2]": {
                            "unk_lgroup[2]": {
                                "unk_varInt[11]": 13,
                                "unk_varInt[14]": 3,
                            },
                            "unk_varInt[1]": 3,
                        },
                        "unk_varInt[3]": 1664913600,
                        "unk_varInt[4]": 3,
                    },
                    "unk_varInt[1]": 3,
                },
                "unk_lgroup[2]": {
                    "unk_lgroup[11]": {
                        "unk_lgroup[13]": {
                            "unk_lgroup[2]": {
                                "unk_lgroup[9]": {
                                    "unk_varInt[1]": 100057,
                                    "unk_varInt[2]": 5,
                                },
                                "unk_varInt[7]": 30236,
                            },
                            "unk_varInt[1]": 30236,
                        },
                    },
                    "unk_varInt[366]": 1,
                },
                "unk_lgroup[4]": {
                    "unk_lgroup[2]": {
                        "unk_lgroup[2]": {
                            "unk_lgroup[2]": {
                                "unk_varInt[10]": 21,
                                "unk_varInt[1]": 3,
                            },
                            "unk_varInt[1]": 5,
                        },
                        "unk_varInt[15]": 3,
                        "unk_varInt[1]": 1664913600,
                    },
                    "unk_varInt[1]": 3,
                },
                "unk_lgroup[7]": {
                    "unk_lgroup[2]": {
                        "unk_varInt[10]": 1664913600,
                        "unk_varInt[7]": 3,
                    },
                    "unk_varInt[1]": 3,
                },
                "unk_string[5]": "",
            },
            watcher_info_list: [
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016047,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016046,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016045,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016044,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016043,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016042,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016040,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016039,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016038,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016036,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016035,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016034,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016033,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016032,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016031,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016030,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016029,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016028,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016027,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016026,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016025,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016011,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016010,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016009,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016008,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016007,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016006,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016049,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 400,
                    watcher_id: 12016002,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016048,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 200,
                    watcher_id: 12016001,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016024,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 600,
                    watcher_id: 12016003,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 800,
                    watcher_id: 12016004,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1000,
                    watcher_id: 12016005,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016012,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016013,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016015,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016016,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016017,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016018,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016019,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016020,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016021,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016022,
                },
                {
                    cur_progress: 0,
                    is_taken_reward: false,
                    total_progress: 1,
                    watcher_id: 12016023,
                },
            ],
            water_spirit_info: {
                mp_play_id: 0,
                region_search_id: 0,
                search_time_map: {},
            },
            winter_camp_info: {
                Unk2700_CFENLEBIKGG: [],
                Unk2700_DKCGOPBHJHA: [],
                Unk2700_FBMHFJHDJNB: [],
                Unk2700_GALHBPGEGNL: [],
                Unk2700_OOBOCEALLBE: [],
                battle_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                explore_info: {
                    cur_progress: 0,
                    id: 0,
                    is_finished: false,
                    open_time: 0,
                    pos: {
                        x: 0,
                        y: 0,
                        z: 0,
                    },
                    total_progress: 0,
                },
                is_content_closed: false,
            },
        },
    ]);
}
